/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "weather_constants.h"

namespace Weather {

const weatherConstants g_weather_constants;

weatherConstants::weatherConstants() {
}

} // namespace

