/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef display_CONSTANTS_H
#define display_CONSTANTS_H

#include "display_types.h"

namespace person {

class displayConstants {
 public:
  displayConstants();

};

extern const displayConstants g_display_constants;

} // namespace

#endif
